// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_boilerplate/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:dio/dio.dart' as _i11;
import 'package:flutter/material.dart' as _i7;
import 'package:flutter_boilerplate/core/common_imports/service_imports.dart'
    as _i2;
import 'package:flutter_boilerplate/core/network/deo_client.dart' as _i3;
import 'package:flutter_boilerplate/core/network/models/api_response.dart'
    as _i4;
import 'package:flutter_boilerplate/data/model/Person.dart' as _i10;
import 'package:flutter_boilerplate/services/gallery_service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:photo_manager/photo_manager.dart' as _i13;
import 'package:stacked_services/stacked_services.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDioClient_1 extends _i1.SmartFake implements _i3.DioClient {
  _FakeDioClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_2<T> extends _i1.SmartFake
    implements _i4.ApiResponse<T> {
  _FakeApiResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i5.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i7.GlobalKey<_i7.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i7.GlobalKey<_i7.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i5.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<T?>? navigateWithTransition<T>(
    _i7.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i7.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i5.Transition? transitionClass,
    _i5.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? replaceWithTransition<T>(
    _i7.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i7.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i5.Transition? transitionClass,
    _i5.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i7.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i7.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? navigateToView<T>(
    _i7.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i7.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i5.Transition? transition,
    _i5.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i7.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? clearStackAndShowView<T>(
    _i7.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? clearTillFirstAndShowView<T>(
    _i7.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);

  @override
  _i8.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i7.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i8.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i5.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i5.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i5.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i8.Future<_i5.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i8.Future<_i5.SheetResponse<dynamic>?>.value(),
      ) as _i8.Future<_i5.SheetResponse<dynamic>?>);

  @override
  _i8.Future<_i5.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i9.Color? barrierColor = const _i9.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i8.Future<_i5.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i8.Future<_i5.SheetResponse<T>?>.value(),
      ) as _i8.Future<_i5.SheetResponse<T>?>);

  @override
  void completeSheet(_i5.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i5.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i5.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i7.Widget Function(
      _i7.BuildContext,
      _i5.DialogRequest<dynamic>,
      dynamic Function(_i5.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i5.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i9.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i9.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i7.RouteSettings? routeSettings,
    _i7.GlobalKey<_i7.NavigatorState>? navigatorKey,
    _i5.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i8.Future<_i5.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i8.Future<_i5.DialogResponse<dynamic>?>.value(),
      ) as _i8.Future<_i5.DialogResponse<dynamic>?>);

  @override
  _i8.Future<_i5.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i9.Color? barrierColor = const _i9.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i7.RouteSettings? routeSettings,
    _i7.GlobalKey<_i7.NavigatorState>? navigatorKey,
    _i7.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i8.Future<_i5.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i8.Future<_i5.DialogResponse<T>?>.value(),
      ) as _i8.Future<_i5.DialogResponse<T>?>);

  @override
  _i8.Future<_i5.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i9.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i9.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i7.RouteSettings? routeSettings,
    _i5.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i8.Future<_i5.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i8.Future<_i5.DialogResponse<dynamic>?>.value(),
      ) as _i8.Future<_i5.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i5.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  @override
  T? read<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  _i8.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> erase() => (super.noSuchMethod(
        Invocation.method(
          #erase,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [EnvironmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentService extends _i1.Mock
    implements _i2.EnvironmentService {
  @override
  _i2.Environment get currentEnvironment => (super.noSuchMethod(
        Invocation.getter(#currentEnvironment),
        returnValue: _i2.Environment.development,
        returnValueForMissingStub: _i2.Environment.development,
      ) as _i2.Environment);

  @override
  bool get isDevelopment => (super.noSuchMethod(
        Invocation.getter(#isDevelopment),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isProduction => (super.noSuchMethod(
        Invocation.getter(#isProduction),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setEnvironment(_i2.Environment? environment) => super.noSuchMethod(
        Invocation.method(
          #setEnvironment,
          [environment],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  @override
  _i2.StorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
        returnValueForMissingStub: _FakeStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i2.StorageService);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i3.DioClient get dioClient => (super.noSuchMethod(
        Invocation.getter(#dioClient),
        returnValue: _FakeDioClient_1(
          this,
          Invocation.getter(#dioClient),
        ),
        returnValueForMissingStub: _FakeDioClient_1(
          this,
          Invocation.getter(#dioClient),
        ),
      ) as _i3.DioClient);

  @override
  bool get isCacheEnabled => (super.noSuchMethod(
        Invocation.getter(#isCacheEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isCacheEnabled(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isCacheEnabled,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i8.Future<_i4.ApiResponse<_i10.Person?>> register(_i10.Person? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [user],
        ),
        returnValue: _i8.Future<_i4.ApiResponse<_i10.Person?>>.value(
            _FakeApiResponse_2<_i10.Person?>(
          this,
          Invocation.method(
            #register,
            [user],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ApiResponse<_i10.Person?>>.value(
                _FakeApiResponse_2<_i10.Person?>(
          this,
          Invocation.method(
            #register,
            [user],
          ),
        )),
      ) as _i8.Future<_i4.ApiResponse<_i10.Person?>>);

  @override
  _i8.Future<_i10.Person?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i8.Future<_i10.Person?>.value(),
        returnValueForMissingStub: _i8.Future<_i10.Person?>.value(),
      ) as _i8.Future<_i10.Person?>);

  @override
  _i8.Future<bool> initializeUser() => (super.noSuchMethod(
        Invocation.method(
          #initializeUser,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i4.ApiResponse<T>> get<T>(
    String? endpoint, {
    Map<String, dynamic>? queryParams,
    bool? useCache,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #queryParams: queryParams,
            #useCache: useCache,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #queryParams: queryParams,
              #useCache: useCache,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #queryParams: queryParams,
              #useCache: useCache,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResponse<T>>);

  @override
  _i8.Future<_i4.ApiResponse<T>> post<T>(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    bool? useCache,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #data: data,
            #queryParams: queryParams,
            #useCache: useCache,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #data: data,
              #queryParams: queryParams,
              #useCache: useCache,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #data: data,
              #queryParams: queryParams,
              #useCache: useCache,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResponse<T>>);

  @override
  _i8.Future<_i4.ApiResponse<T>> patch<T>(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {
            #data: data,
            #queryParams: queryParams,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #patch,
            [endpoint],
            {
              #data: data,
              #queryParams: queryParams,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #patch,
            [endpoint],
            {
              #data: data,
              #queryParams: queryParams,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResponse<T>>);

  @override
  _i8.Future<_i4.ApiResponse<T>> delete<T>(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #data: data,
            #queryParams: queryParams,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #data: data,
              #queryParams: queryParams,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ApiResponse<T>>.value(_FakeApiResponse_2<T>(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #data: data,
              #queryParams: queryParams,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResponse<T>>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateCache(
    String? endpoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [endpoint],
          {#queryParams: queryParams},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #updateAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T? parseDataField<T>(_i4.ApiResponse<Map<String, dynamic>>? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseDataField,
          [response],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  Map<String, dynamic>? parsePaginatedResponse(
          _i4.ApiResponse<Map<String, dynamic>>? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #parsePaginatedResponse,
          [response],
        ),
        returnValueForMissingStub: null,
      ) as Map<String, dynamic>?);

  @override
  String getErrorMessage(_i4.ApiResponse<dynamic>? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #getErrorMessage,
          [response],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getErrorMessage,
            [response],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getErrorMessage,
            [response],
          ),
        ),
      ) as String);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GalleryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalleryService extends _i1.Mock implements _i12.GalleryService {
  @override
  int get pageSize => (super.noSuchMethod(
        Invocation.getter(#pageSize),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set pageSize(int? _pageSize) => super.noSuchMethod(
        Invocation.setter(
          #pageSize,
          _pageSize,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i13.AssetEntity> get accessibleAssets => (super.noSuchMethod(
        Invocation.getter(#accessibleAssets),
        returnValue: <_i13.AssetEntity>[],
        returnValueForMissingStub: <_i13.AssetEntity>[],
      ) as List<_i13.AssetEntity>);

  @override
  List<_i13.AssetPathEntity> get albums => (super.noSuchMethod(
        Invocation.getter(#albums),
        returnValue: <_i13.AssetPathEntity>[],
        returnValueForMissingStub: <_i13.AssetPathEntity>[],
      ) as List<_i13.AssetPathEntity>);

  @override
  _i13.PermissionState get permissionState => (super.noSuchMethod(
        Invocation.getter(#permissionState),
        returnValue: _i13.PermissionState.notDetermined,
        returnValueForMissingStub: _i13.PermissionState.notDetermined,
      ) as _i13.PermissionState);

  @override
  bool get hasFullAccess => (super.noSuchMethod(
        Invocation.getter(#hasFullAccess),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasLimitedAccess => (super.noSuchMethod(
        Invocation.getter(#hasLimitedAccess),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasAnyAccess => (super.noSuchMethod(
        Invocation.getter(#hasAnyAccess),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get permissionStatusMessage => (super.noSuchMethod(
        Invocation.getter(#permissionStatusMessage),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#permissionStatusMessage),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#permissionStatusMessage),
        ),
      ) as String);

  @override
  bool get hasEffectiveFullAccess => (super.noSuchMethod(
        Invocation.getter(#hasEffectiveFullAccess),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.Future<_i13.PermissionState> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i8.Future<_i13.PermissionState>.value(
            _i13.PermissionState.notDetermined),
        returnValueForMissingStub: _i8.Future<_i13.PermissionState>.value(
            _i13.PermissionState.notDetermined),
      ) as _i8.Future<_i13.PermissionState>);

  @override
  _i8.Future<void> loadAccessibleContent() => (super.noSuchMethod(
        Invocation.method(
          #loadAccessibleContent,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i13.AssetEntity>> getAssetsFromAlbum(
    _i13.AssetPathEntity? album, {
    int? page = 0,
    int? size = 200,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssetsFromAlbum,
          [album],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i8.Future<List<_i13.AssetEntity>>.value(<_i13.AssetEntity>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i13.AssetEntity>>.value(<_i13.AssetEntity>[]),
      ) as _i8.Future<List<_i13.AssetEntity>>);

  @override
  _i8.Future<List<_i13.AssetEntity>> loadMoreAssetsFromAlbum(
    _i13.AssetPathEntity? album,
    int? currentCount, {
    int? pageSize = 200,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreAssetsFromAlbum,
          [
            album,
            currentCount,
          ],
          {#pageSize: pageSize},
        ),
        returnValue:
            _i8.Future<List<_i13.AssetEntity>>.value(<_i13.AssetEntity>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i13.AssetEntity>>.value(<_i13.AssetEntity>[]),
      ) as _i8.Future<List<_i13.AssetEntity>>);

  @override
  _i8.Future<bool> requestMorePhotos() => (super.noSuchMethod(
        Invocation.method(
          #requestMorePhotos,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> openAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #openAppSettings,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> getAlbumAssetCount(_i13.AssetPathEntity? album) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlbumAssetCount,
          [album],
        ),
        returnValue: _i8.Future<int>.value(0),
        returnValueForMissingStub: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> hasMoreAssets(
    _i13.AssetPathEntity? album,
    int? currentCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasMoreAssets,
          [
            album,
            currentCount,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
